export const REPO_CONFIG = {
  'prebidjs': {
    slug: 'prebidjs',
    key: 'prebid-js',
    storeKey: 'prebid-js',
    name: 'Prebid.js',
    displayName: 'Prebid.js',
    owner: 'prebid',
    repo: 'Prebid.js',
    url: 'https://github.com/prebid/Prebid.js',
    description: 'Client-side header bidding wrapper',
    category: 'Client' as const,
  },
  'prebidserver': {
    slug: 'prebidserver',
    key: 'prebid-server',
    storeKey: 'prebid-server',
    name: 'Prebid Server',
    displayName: 'Prebid Server (Go)',
    owner: 'prebid',
    repo: 'prebid-server',
    url: 'https://github.com/prebid/prebid-server',
    description: 'Server-side header bidding',
    category: 'Server' as const,
  },
  'prebidserverjava': {
    slug: 'prebidserverjava',
    key: 'prebid-server-java',
    storeKey: 'prebid-server-java',
    name: 'Prebid Server Java',
    displayName: 'Prebid Server (Java)',
    owner: 'prebid',
    repo: 'prebid-server-java',
    url: 'https://github.com/prebid/prebid-server-java',
    description: 'Server-side header bidding (Java implementation)',
    category: 'Server' as const,
  },
  'prebidmobileios': {
    slug: 'prebidmobileios',
    key: 'prebid-mobile-ios',
    storeKey: 'prebid-mobile-ios',
    name: 'Prebid Mobile iOS',
    displayName: 'Prebid Mobile (iOS)',
    owner: 'prebid',
    repo: 'prebid-mobile-ios',
    url: 'https://github.com/prebid/prebid-mobile-ios',
    description: 'Mobile header bidding for iOS',
    category: 'Mobile' as const,
  },
  'prebidmobileandroid': {
    slug: 'prebidmobileandroid',
    key: 'prebid-mobile-android',
    storeKey: 'prebid-mobile-android',
    name: 'Prebid Mobile Android',
    displayName: 'Prebid Mobile (Android)',
    owner: 'prebid',
    repo: 'prebid-mobile-android',
    url: 'https://github.com/prebid/prebid-mobile-android',
    description: 'Mobile header bidding for Android',
    category: 'Mobile' as const,
  },
  'prebiddocs': {
    slug: 'prebiddocs',
    key: 'prebid-github-io',
    storeKey: 'prebid-github-io',
    name: 'Prebid Docs',
    displayName: 'Prebid Documentation',
    owner: 'prebid',
    repo: 'prebid.github.io',
    url: 'https://github.com/prebid/prebid.github.io',
    description: 'Official Prebid documentation',
    category: 'Docs' as const,
  },
} as const;

export type RepoSlug = keyof typeof REPO_CONFIG;
export type RepoCategory = 'Client' | 'Server' | 'Mobile' | 'Docs';
export const VALID_SLUGS = Object.keys(REPO_CONFIG) as RepoSlug[];
